### PR TITLE
Replace back arrow with logout button

### PR DESCRIPTION
**Pull request by cdawei**
# Pull Request Details

## What issue does this PR address

- Add a logout button in the test page

- Link to associated issue: #69 

## Checklist

Complete the check-list below to ensure your branch is ready for PR.

Flutter Style Guide: https://survivor.togaware.com/gnulinux/flutter-style.html

- [ ] Screenshots included in linked issue
- [x] Changes adhere to the team style and coding guideline
- [x] No confidential information
- [x] No duplicated content
- [ ] No lint check errors related to your changes (`make prep` or `flutter analyze lib`)
- [ ] Pre-exisiting lint errors noted: [HERE]
- [x] Tested on at least one device
  - [ ] Android Phone
  - [ ] Android Emulator
  - [ ] Chrome on Android
  - [ ] Chrome
  - [ ] iOS
  - [x] Linux
  - [ ] MacOS
  - [ ] Windows
- [x] Added 2 reviewers (or 1 for private repositories then they add another)

## Finalising

Once PR discussion is complete and 2 reviewers have approved:

- [ ] Merge dev into the branch
- [ ] Resolve any conflicts
- [ ] Add one line summary into CHANGELOG.md
- [ ] Bump appropriate version number in pubspec.yaml
- [ ] Push to git repository and review
- [ ] Merge PR into dev

### CODE REVIEW

**Review by junhaow1 — APPROVED** [review]

**Review by gjwgit — CHANGES_REQUESTED** [review]
Could we have this as another button with the collection of buttons on the test page for LOGOUT POD and no top row icon on the left. Thanks.

**Comment by cdawei** [comment]
> Could we have this as another button with the collection of buttons on the test page for LOGOUT POD and no top row icon on the left. Thanks.

Here's a screenshot of the new position of the logout button.
logout

**Comment by cdawei** [comment]
See also additional discussion here https://github.com/anusii/keypod/issues/69

**Comment by cdawei** [comment]
A logout button that uses the logout popup in `solidpod` is implemented in `keypod`. Does that implement the requested changes from you @gjwgit ?

**Review by gjwgit — APPROVED** [review]

**Pull request merged**
