### PR TITLE
kev/84_redesign

### PR DESCRIPTION
**Pull request by junhaow1**
# Pull Request Details

## What issue does this PR address

- • KeyValue Table becomes the first page (home) of the app. Replace Home button with Testing to go to the testing page.

- Link to associated issue: 
  - #84
  - #96  

## Checklist

Complete the check-list below to ensure your branch is ready for PR.

Flutter Style Guide: https://survivor.togaware.com/gnulinux/flutter-style.html

- [x] Screenshots included in linked issue
- [x] Changes adhere to the team style and coding guideline
- [x] No confidential information
- [x] No duplicated content
- [x] No lint check errors related to your changes (`make prep` or `flutter analyze lib`)
- [ ] Pre-exisiting lint errors noted: [HERE]
- [x] Tested on at least one device
  - [ ] Android Phone
  - [ ] Android Emulator
  - [ ] Chrome on Android
  - [x] Chrome
  - [ ] iOS
  - [ ] Linux
  - [ ] MacOS
  - [ ] Windows
- [x] Added 2 reviewers (or 1 for private repositories then they add another)

## Finalising

Once PR discussion is complete and 2 reviewers have approved:

- [ ] Merge dev into the branch
- [ ] Resolve any conflicts
- [ ] Add one line summary into CHANGELOG.md
- [ ] Bump appropriate version number in pubspec.yaml
- [ ] Push to git repository and review
- [ ] Merge PR into dev

### CODE REVIEW

**Comment by cdawei** [comment]
It seems I can add the same key twice in the editor but when I click **Save**, it leads to an exception (see below).
Do we need to check if there is any duplicate keys before saving to POD?
duplicate_keys
```bash
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:keypod/utils/rdf.dart': Failed assertion: line 42 pos 10: '{for (final p in keyValuePairs) p.key}.length ==
      keyValuePairs.length': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      genTTLStr (package:keypod/utils/rdf.dart:42:10)
#3      _KeyValueTableState._saveToPod (package:keypod/screens/data_table.dart:199:28)
#4      _KeyValueTableState.build.<anonymous closure> (package:keypod/screens/data_table.dart:245:41)
#5      _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1171:21)
#6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:344:24)
#7      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:652:11)
#8      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:309:5)
#9      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:242:7)
#10     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:696:9)
#11     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:98:12)
#12     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:143:9)
#13     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:633:13)
#14     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:141:18)
#15     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:127:7)
#16     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:495:19)
#17     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:475:22)
#18     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:425:11)
#19     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:420:7)
#20     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:383:5)
#21     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:330:7)
#22     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:299:9)
#23     _invoke1 (dart:ui/hooks.dart:328:13)
#24     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:442:7)
#25     _dispatchPointerDataPacket (dart:ui/hooks.dart:262:31)
```

**Comment by junhaow1** [comment]
> It seems I can add the same key twice in the editor but when I click **Save**, it leads to an exception (see below). Do we need to check if there is any duplicate keys before saving to POD? duplicate_keys
> 
> ```shell
> [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:keypod/utils/rdf.dart': Failed assertion: line 42 pos 10: '{for (final p in keyValuePairs) p.key}.length ==
>       keyValuePairs.length': is not true.
> #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
> #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
> #2      genTTLStr (package:keypod/utils/rdf.dart:42:10)
> #3      _KeyValueTableState._saveToPod (package:keypod/screens/data_table.dart:199:28)
> #4      _KeyValueTableState.build.<anonymous closure> (package:keypod/screens/data_table.dart:245:41)
> #5      _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1171:21)
> #6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:344:24)
> #7      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:652:11)
> #8      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:309:5)
> #9      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:242:7)
> #10     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:696:9)
> #11     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:98:12)
> #12     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:143:9)
> #13     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:633:13)
> #14     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:141:18)
> #15     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:127:7)
> #16     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:495:19)
> #17     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:475:22)
> #18     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:425:11)
> #19     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:420:7)
> #20     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:383:5)
> #21     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:330:7)
> #22     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:299:9)
> #23     _invoke1 (dart:ui/hooks.dart:328:13)
> #24     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:442:7)
> #25     _dispatchPointerDataPacket (dart:ui/hooks.dart:262:31)
> ```

Thanks @cdawei  for finding this  , https://github.com/anusii/keypod/issues/96 created to resolve this issue

**Review by gjwgit — APPROVED** [review]
Looks great. Thanks.

Could probably drop the about icon on the first page while logging in:

image

Do we need that first page at all?

**Comment by junhaow1** [comment]
> Do we need that first page at all?

It is necessary to keep the first page to call _writePrivateData(), which prepares the initialization of the key-value pair datatable.

**Review by cdawei — APPROVED** [review]

**Pull request merged**
