### PR TITLE
Zy/131 add webid about

### LINKED ISSUE #131: KEYPOD: Add WebID to the About popup
A user can not see their webID after logging in and would like to.

Image

### PR DESCRIPTION
**Pull request by zheyxu**
# Pull Request Details

## What issue does this PR address

- KEYPOD: Add WebID to the About popup

- Link to associated issue: #131

## Checklist

Complete the check-list below to ensure your branch is ready for PR.

Flutter Style Guide: https://survivor.togaware.com/gnulinux/flutter-style.html

- [x] Screenshots included in linked issue
- [x] Changes adhere to the team style and coding guideline
- [x] No confidential information
- [x] No duplicated content
- [x] No lint check errors related to your changes (`make prep` or `flutter analyze lib`)
- [x] Pre-exisiting lint errors noted: [HERE]
- [x] Tested on at least one device
  - [ ] Android Phone
  - [ ] Android Emulator
  - [ ] Chrome on Android
  - [ ] Chrome
  - [ ] iOS
  - [ ] Linux
  - [x] MacOS
  - [ ] Windows
- [x] Added 2 reviewers (or 1 for private repositories then they add another)

## Finalising

Once PR discussion is complete and 2 reviewers have approved:

- [ ] Merge dev into the branch
- [ ] Resolve any conflicts
- [ ] Add one line summary into CHANGELOG.md
- [ ] Bump appropriate version number in pubspec.yaml
- [ ] Push to git repository and review
- [ ] Merge PR into dev

### CODE REVIEW

**Review by anushkavidanage — APPROVED** [review]

**Comment by cdawei** [comment]
Shall we have the WebID in this page as well?
webId

**Review by cdawei — COMMENTED** [review]
Please show WebID in `app.dart` here as well https://github.com/anusii/keypod/blob/bbb613bc851d60aa6862b695e9b78b535ba72706/lib/app.dart#L54

**Comment by zheyxu** [comment]
> Please show WebID in `app.dart` here as well
> 
> https://github.com/anusii/keypod/blob/bbb613bc851d60aa6862b695e9b78b535ba72706/lib/app.dart#L54
The page right after login has no webId. 

To show webId after login page, the code in solidPod should be updated.

https://github.com/anusii/keypod/blob/b54175f63d695a5991dfbbb51caaba7fb1b512f0/lib/main.dart#L102-L130


Screenshot 2024-07-18 at 9 15 03 PM

However, after login and get to page second time, webId is shown.

Screenshot 2024-07-18 at 9 18 29 PM

**Comment by cdawei** [comment]
> To show webId after login page, the code in solidPod should be updated.

Hi @zheyxu, this has been done in `solidpod/demopod` using `FutureBuilder`, could you have a look at this? https://github.com/anusii/solidpod/blob/c0bb2c25928f852c1c4281a80cbfbc3f8a6269e9/demopod/lib/home.dart#L504

**Comment by zheyxu** [comment]
> > To show webId after login page, the code in solidPod should be updated.
> 
> Hi @zheyxu, this has been done in `solidpod/demopod` using `FutureBuilder`, could you have a look at this? https://github.com/anusii/solidpod/blob/c0bb2c25928f852c1c4281a80cbfbc3f8a6269e9/demopod/lib/home.dart#L504

The issue was fixed, thanks!

**Comment by cdawei** [comment]
> > Hi @zheyxu, this has been done in `solidpod/demopod` using `FutureBuilder`, could you have a look at this? https://github.com/anusii/solidpod/blob/c0bb2c25928f852c1c4281a80cbfbc3f8a6269e9/demopod/lib/home.dart#L504
> 
> The issue was fixed, thanks!

Thanks @zheyxu. Can we just show some text (for example, "Not Logged In") if the user is not logged in? 
Currently, I got a loading animation as shown below.
webId

**Comment by zheyxu** [comment]
> > > Hi @zheyxu, this has been done in `solidpod/demopod` using `FutureBuilder`, could you have a look at this? https://github.com/anusii/solidpod/blob/c0bb2c25928f852c1c4281a80cbfbc3f8a6269e9/demopod/lib/home.dart#L504
> > 
> > 
> > The issue was fixed, thanks!
> 
> Thanks @zheyxu. Can we just show some text (for example, "Not Logged In") if the user is not logged in? Currently, I got a loading animation as shown below. webId

Hi @cdawei, I don't have the issue. Even I registered a new user, still got the webId.
Screenshot 2024-07-19 at 10 24 47 AM

**Comment by zheyxu** [comment]
@cdawei The issue is fixed now.
Screenshot 2024-07-19 at 10 41 25 AM

**Review by cdawei — APPROVED** [review]

**Pull request merged**
