### PR TITLE
Kev/48_data_table

### PR DESCRIPTION
**Pull request by junhaow1**
# Pull Request Details

## What issue does this PR address

- added  a widget to view, insert, edit, delete rows of key-value pairs

- Link to associated issue: #48 

## Checklist

Complete the check-list below to ensure your branch is ready for PR.

Flutter Style Guide: https://survivor.togaware.com/gnulinux/flutter-style.html

- [x] Screenshots included in linked issue
- [x] Changes adhere to the team style and coding guideline
- [x] No confidential information
- [x] No duplicated content
- [x] No lint check errors related to your changes (`make prep` or `flutter analyze lib`)
- [ ] Pre-exisiting lint errors noted: [HERE]
- [x] Tested on at least one device
  - [ ] Android Phone
  - [ ] Android Emulator
  - [ ] Chrome on Android
  - [x] Chrome
  - [ ] iOS
  - [ ] Linux
  - [ ] MacOS
  - [ ] Windows
- [x] Added 2 reviewers (or 1 for private repositories then they add another)

## Finalising

Once PR discussion is complete and 2 reviewers have approved:

- [ ] Merge dev into the branch
- [ ] Resolve any conflicts
- [ ] Add one line summary into CHANGELOG.md
- [ ] Bump appropriate version number in pubspec.yaml
- [ ] Push to git repository and review
- [ ] Merge PR into dev

### CODE REVIEW

**Comment by gjwgit** [comment]
When I type a key string, the string is entered in reverse order. I've seen this before in another app - requires some tuning but I forget the details.

**Comment by junhaow1** [comment]
> In the below I typed ghi, 789, jkl, 123 - all have come out backwards.

on it. should not be long

**Review by gjwgit — COMMENTED** [review]
Also, when the SAVE button is active the Go Back should either not be active (but then would need a UNDO) or else if I click GO BACK then it should ask me if I am sure since I will loose all updates as they have not been saved.

**Comment by junhaow1** [comment]
> Also, when the SAVE button is active the Go Back should either not be active (but then would need a UNDO) or else if I click GO BACK then it should ask me if I am sure since I will loose all updates as they have not been saved.
> 
> I think you already have an UNDO? by clicking on the top left back arrow - is that the intent?

fixed 
image

**Review by gjwgit — APPROVED** [review]
Tested and working very nicely on ubuntu desktop. Excellent. Thanks @junhaow1

**Review by cdawei — APPROVED** [review]
Nice work!

**Pull request merged**
